version: '3'

services:
  irods-provider-tempzone:
    build:
        context: .
        dockerfile: Dockerfile.provider
    hostname: icat.tempZone.example.org
    networks:
      default:
        aliases:
          - icat.tempZone.example.org
    volumes:
      - ./configure_federation_tempZone.py:/configure_federation.py:ro
      - /home/alanking/projects/builds:/builds:ro
      - /home/alanking/projects/irods_repos/irods:/irods_source:ro
      - /home/alanking/projects/irods_repos/irods_client_icommands:/icommands_source:ro
    environment:
      - REMOTE_ZONE=otherZone
      - REMOTE_HOST=icat.otherZone.example.org
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
  irods-provider-otherzone:
    build:
        context: .
        dockerfile: Dockerfile.provider.otherZone
    hostname: icat.otherZone.example.org
    networks:
      default:
        aliases:
          - icat.otherZone.example.org
    volumes:
      - ./configure_federation_otherZone.py:/configure_federation.py:ro
      - /home/alanking/projects/builds:/builds:ro
      - /home/alanking/projects/irods_repos/irods:/irods_source:ro
      - /home/alanking/projects/irods_repos/irods_client_icommands:/icommands_source:ro
    environment:
      - REMOTE_ZONE=tempZone
      - REMOTE_HOST=icat.tempZone.example.org
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
